import Navbar from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-myWhite`}>
      <Navbar/>
      <hr className='w-100 h-1 bg-gray-200 border-0 rounded dark:bg-gray-700'/>
      <div className='max-w-[90%] mx-auto '>
        
        
        <h1>layout wala page pehly show hoga</h1>
        {children}
        
      </div>
      <hr className='w-100 h-1 bg-gray-200 border-0 rounded dark:bg-gray-700'/>
        
      <Footer />
      </body>
    </html>
  )
}
